/**
 * Superseded by `scripts/generate-icons.py`.
 *
 * Icons used to be a procedurally-drawn cross; they're now derived from the
 * church crest (assets/logo-source.png), which needs real image resizing, so
 * generation moved to Python (Pillow). `npm run icons` runs the Python script.
 *
 * This file only remains to stop a stale `node scripts/generate-icons.mjs`
 * from silently overwriting the crest icons with the old cross.
 */
console.error('Icons are now generated by scripts/generate-icons.py — run: npm run icons');
process.exit(1);
